### ISSUE TITLE
need advice on performance in FFTW

### ISSUE THREAD

**Issue by epsi1on** [wo80/SharpFFTW#10]
Hi there,
I'm trying to use the FFTW in a software which is calling the FFTW on a very long array continuously (like 10 times per second).
the size of array is `short[500'000]` maybe even to `byte[50'000'000]`. i was looking through the code and realized that for every time FFTW is calculating FFT, it is re allocating the memory. in my case, it can end up allocating a 100MB array, 10 times a second which i'm not sure if it is good idea.

- Is there any method to pass the array into FFTW instead of creating it everytime? does it even have impact on performance?
- If above answer is yes, is there any method to input the length of array too? for example i am passing an array with length 100k but only first 5k is filled and rest is empty, because i'm using array pool in C#.

Thanks for great work...

**Comment by wo80** [comment]
Not sure if I understand correctly, but say you have some signal source that is feeding some data continuously to your program.
You either
1) create a buffer and copy the incoming data to it (you need to know how large the data packets that are coming in are and make the buffer large enough) _or_
2) directly use the incoming data (`byte` or `short` array)

No need to allocate new memory each time data comes in. Obviously, you need to decide beforehand what size your FFT should be and **you want this to be independent of the size of the incoming data**! You will probably need another buffer with the size of the FFT and copy the buffer holding the incoming data in chunks. 

So as an example, lets say your signal source sends data as `byte[50000000]`. That data could be interpreted as `float[12500000]`. To process one such packet, you would call a FFT of size 8192 (2^13) 1525 times - or even more, if you want to have the chunks overlap.
