### ISSUE TITLE
Crash with munmap_chunk invalid pointer

### ISSUE THREAD

**Issue by rsulab** [wo80/SharpFFTW#6]
Hi

Sometimes i got thus error on code:

 ```
           var real = new float[points.Length];
           using var input = new RealArray(real);
            using var output = new ComplexArray(points.Length / 2 + 1);
            using var plan = Plan.Create1(points.Length, input, output, Options.Estimate);

            plan.Execute();
```

**Comment by wo80** [comment]
Never seen this and I cannot reproduce the error.

What's your OS and what FFTW binary are you using?

**Comment by rsulab** [comment]
> Never seen this and I cannot reproduce the error.
> 
> What's your OS and what FFTW binary are you using?

1. Linux in docker
2. linux-x64

**Comment by wo80** [comment]
So I guess the fftw binary is from an official repo?

Since you are using `using var ...`, are you sure that the memory isn't accessed after going out of scope. You could check the `Dispose` methods of `RealArray/ComplexArray` by writing some debug info to console, something like
```c#
public override void Dispose(bool disposing)
{
    if (!hasDisposed)
    {
        if (Handle != IntPtr.Zero)
        {
            Console.WriteLine("Disposing real/complex array " + Handle); // For debugging purpose.
            NativeMethods.fftw_free(Handle);
            Handle = IntPtr.Zero;
        }
    }

    hasDisposed = disposing;
}
```

**Comment by wo80** [comment]
I think you can forget about my above comment, the freeing of the native memory should be safe.

Are you calling fftw from multiple threads?

Otherwise I'm out of ideas. If you search for `munmap_chunk` you'll find that it's related to freeing native memory. The only place this happen directly in the C# code is in the `Dispose` methods, but the error occurs on the call to `plan.Execute()`, right?

**Comment by rsulab** [comment]
> I think you can forget about my above comment, the freeing of the native memory should be safe.
> 
> Are you calling fftw from multiple threads?
> 
> Otherwise I'm out of ideas. If you search for `munmap_chunk` you'll find that it's related to freeing native memory. The only place this happen directly in the C# code is in the `Dispose` methods, but the error occurs on the call to `plan.Execute()`, right?

yes  from multiple threads

**Comment by wo80** [comment]
I just tested with multiple threads on windows and linux. Should be no problem. According to the FFTW docs, the only thing that's not thread-safe is the plan creation, and that's taken care of with a mutex. I'm really out of ideas now, sorry...

**Comment by wo80** [comment]
According to https://www.fftw.org/fftw3_doc/Thread-safety.html , the only thread-safe method is `plan_execute`, so there still might be a chance that this a multi-threading related issue and methods like `fftw_destroy_plan` should be protected by a mutex too. Since I cannot reproduce the error, could you test this?

**Comment by wo80** [comment]
You might want to test the https://github.com/wo80/SharpFFTW/commits/develop branch. I've rewritten the dispose pattern. Not sure if this will fix your issue, but it's worth a try...

**Comment by rsulab** [comment]
> You might want to test the https://github.com/wo80/SharpFFTW/commits/develop branch. I've rewritten the dispose pattern. Not sure if this will fix your issue, but it's worth a try...

i`ll try your code

**Comment by rsulab** [comment]
> You might want to test the https://github.com/wo80/SharpFFTW/commits/develop branch. I've rewritten the dispose pattern. Not sure if this will fix your issue, but it's worth a try...

i`d tried new code

crash still 

sometimes with message: **double free or corruption (fasttop)** and sometimes with: **free(): invalid pointer**

**Comment by rsulab** [comment]
> using var input = new RealArray(real);
>            using var output = new ComplexArray(points.Length / 2 + 1);
>            using var plan = Plan.Create1(points.Length, input, output, Options.Estimate);
> 
>            plan.Execute();

lock dont help too - double free or corruption (out)

       lock(_sync)
        {
           using var input = new RealArray(real);
           using var output = new ComplexArray(points.Length / 2 + 1);
           using var plan = Plan.Create1(points.Length, input, output, Options.Estimate);

           plan.Execute();
       }
```

**Comment by wo80** [comment]
Which linux os/version and which fftw package are you using in your docker image?

I've added a simple example using `Parallel.For(...)`. This works for me on both windows and linux, see https://github.com/wo80/SharpFFTW/commit/9be35918e6b1a061907e7b117c191a884b1fc899

**Comment by rsulab** [comment]
> Which linux os/version and which fftw package are you using in your docker image?
> 
> I've added a simple example using `Parallel.For(...)`. This works for me on both windows and linux, see [9be3591](https://github.com/wo80/SharpFFTW/commit/9be35918e6b1a061907e7b117c191a884b1fc899)

i use asp docker 

full my code:

```
var block = ActionBlock<DataPoint[]>(async points => {
      var real = new float[points.Length]; 
      for (var index = 0; index < points.Length; index++)
                real[index] = (float) points[index].Value;

       using var input = new RealArray(real);
       using var output = new ComplexArray(points.Length / 2 + 1);
       using var plan = Plan.Create1(points.Length, input, output, Options.Estimate);

       plan.Execute();

       /// ...
});
```

**Comment by rsulab** [comment]
It seems FFTW planner is not threads safe

https://github.com/FFTW/fftw3/issues/176

**Comment by wo80** [comment]
All the plan creation calls are protected by a mutex, for example
https://github.com/wo80/SharpFFTW/blob/ee74cbff0644aeedbbe907a3341d162e49120029/SharpFFTW/Double/Plan.cs#L87-L89

and regarding the error you get (_munmap_chunk_, _double free or corruption (fasttop)_, _free(): invalid pointer_) the issue seems to be the freeing of native memory. So this would point to the `Dispose` implementation.

One thing you could try: compile SharpFFTW with `USE_THREADS` symbol. Using `dotnet` from command line you can call
```
dotnet build /p:DefineConstants="USE_THREADS"
```
When initializing your program, add a call to `SharpFFTW.SingleNativeMethods.fftwf_make_planner_thread_safe();`. Be aware that will only work when the native FFTW library was compiled with `ENABLE_THREADS`.

**Comment by rsulab** [comment]
> All the plan creation calls are protected by a mutex, for example
> 
> https://github.com/wo80/SharpFFTW/blob/ee74cbff0644aeedbbe907a3341d162e49120029/SharpFFTW/Double/Plan.cs#L87-L89
> 
> and regarding the error you get (_munmap_chunk_, _double free or corruption (fasttop)_, _free(): invalid pointer_) the issue seems to be the freeing of native memory. So this would point to the `Dispose` implementation.
> 
> One thing you could try: compile SharpFFTW with `USE_THREADS` symbol. Using `dotnet` from command line you can call
> 
> ```
> dotnet build /p:DefineConstants="USE_THREADS"
> ```
> 
> When initializing your program, add a call to `SharpFFTW.Single.NativeMethods.fftwf_make_planner_thread_safe()`. Be aware that this will only work if the native FFTW library was compiled with `ENABLE_THREADS`.

Yes, creatinon use mutex but fftwf_destroy_plan is not.

            ```
if (handle != IntPtr.Zero)
            {
                NativeMethods.fftwf_destroy_plan(handle);
                handle = IntPtr.Zero;
            }

            if (disposing && ownsArrays)
            {
                input.Dispose();
                output.Dispose();
            } 
```

**Comment by wo80** [comment]
Ok, so the calls to `fftw_destroy_plan` are now protected with a mutex, https://github.com/wo80/SharpFFTW/commit/174d291edf08776691190dcad04a66728df1c77e. Let me know if it works!

**Comment by wo80** [comment]
Any update?

**Comment by wo80** [comment]
Merged the changes.

**Comment by rsulab** [comment]
> Any update?

It seems help, thanks
